### ISSUE TITLE
Sporadic crash running from Xcode

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#107]
Amiko-osx 3.4.16
Running from Xcode, Debug build.
Launch the app and after a few seconds Xcode stops, see screenshot and output log file.

Observed a few times with git commit 31d3caa (29 Jul 2020). Not repeatable.

After updating the sources to git commit cb323bc (31 Jul 2020) it happened 4 times out of 4 attempts. Then I did a "clean" build and it hasn't crashed so far.

**Comment by bettar** [comment]
![Screenshot 2020-08-01 at 11 10 26](https://user-images.githubusercontent.com/9733270/89098600-567b8e00-d3e9-11ea-801e-041cf35805b0.png)

**Comment by bettar** [comment]
[xcode-output.txt](https://github.com/zdavatz/amiko-osx/files/5010123/xcode-output.txt)

**Comment by bettar** [comment]
There was already a mention of this problem in issue #93, which has been closed since #95. The crash I am reporting must be caused by something else, because for me the crash is still happening.

**Comment by zdavatz** [comment]
Please reopen if it happens again after doing the clean build.

**Comment by bettar** [comment]
The last words I wrote were "the crash is still happening."

**Comment by zdavatz** [comment]
what is your version here:
<img width="435" alt="Bildschirmfoto 2020-08-01 um 13 34 00" src="https://user-images.githubusercontent.com/4953/89099948-bf6c0180-d3fb-11ea-8d38-9ff60633a608.png">

**Comment by zdavatz** [comment]
Which Xcode Version?

**Comment by bettar** [comment]
It was 21 Jul 2020. I updated to 1 Aug 2020 and it still crashes

**Comment by bettar** [comment]
Xcode is 11.6

**Comment by zdavatz** [comment]
Does CoMed have the same crash?

**Comment by bettar** [comment]
yes

**Comment by zdavatz** [comment]
Did you update the Database with `Apple+A`?

**Comment by zdavatz** [comment]
@bettar is is enabled on your Mac? <img width="765" alt="Bildschirmfoto 2020-08-01 um 14 33 18" src="https://user-images.githubusercontent.com/4953/89100944-445b1900-d404-11ea-8917-eaa9aac72887.png">

**Comment by zdavatz** [comment]
do have this enabled?

<img width="554" alt="Bildschirmfoto 2020-08-01 um 14 39 21" src="https://user-images.githubusercontent.com/4953/89101004-d4995e00-d404-11ea-9e04-c82132c127eb.png">

**Comment by b123400** [comment]
I think it's a bug by Apple, that we can do nothing to solve it. The app does not crash unless it's connected to Xcode, so it's good that our user won't be affected.

Related:

https://stackoverflow.com/questions/58758353/exc-bad-instruction-from-com-apple-xpc-activity-com-apple-cloudkit-scheduler-com
https://stackoverflow.com/questions/61139159/how-to-debug-core-data-cloudkit-crash-on-macos-app
https://developer.apple.com/forums/thread/650230
