### ISSUE TITLE
CoMed naming issues

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#108]
![image](https://user-images.githubusercontent.com/4953/89226012-e2590a00-d5e3-11ea-87d8-97096b50b45b.jpeg)

**Comment by zdavatz** [comment]
The App name should always be `CoMed Desitin`no matter what language the interface is.

<img width="427" alt="Bildschirmfoto 2020-08-04 um 13 29 02" src="https://user-images.githubusercontent.com/4953/89283866-8da2a700-d656-11ea-8325-bb7a117e0d26.png">

**Comment by zdavatz** [comment]
The icon should be blue as well. 
<img width="417" alt="Bildschirmfoto 2020-08-04 um 13 36 48" src="https://user-images.githubusercontent.com/4953/89284538-9a73ca80-d657-11ea-9b51-74461a50faca.png">

**Comment by bettar** [comment]
It's worth noting that If CoMed is used in French there is no problem with the menu labels. This was deemed acceptable when the menu localisation was introduced. Unfortunately Apple is not satisfied with that limitation.

**Comment by bettar** [comment]
Apple complains about "name in binary: AmiKo Desitin". What's the filename in `CoMed Desitin.app/Contents/MacOS/` of the app that was submitted ?

**Comment by zdavatz** [comment]
How do I check this? I am just running the build script.

**Comment by zdavatz** [comment]
<img width="666" alt="Bildschirmfoto 2020-08-07 um 13 45 59" src="https://user-images.githubusercontent.com/4953/89638354-54677280-d8b4-11ea-8c0c-3b8ee8b01ff5.png">

**Comment by bettar** [comment]
That's not the file you submitted because it was built today, and Apple report was 4 days ago

**Comment by zdavatz** [comment]
I the one I submitted has been deleted.

**Comment by zdavatz** [comment]
![image](https://user-images.githubusercontent.com/4953/89706452-702f4f00-d96e-11ea-941b-2e48357cd468.png)
