### ISSUE TITLE
iOS/macOS sync issues

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#109]
1. The favorites got synced from macOS to iOS, but the prescription from macOS doesn’t show up on iOS. It’s not listed in the right swipe panel, and I can only see the the doctor’s name, no patient data no medicines.

2. Syncing FTS Favorites from macOS to iOS crashes the iOS App. Normal Favorites work.

**Comment by zdavatz** [comment]
is the file format for `Favorites` the same for `macOS` and `iOS`?

**Comment by b123400** [comment]
1. Favourites and prescriptions files are synced via iCloud document, they are actual files. While patient data is in a database, that is synced via CloudKit. I think it's possible the CloudKit sync is not configured correctly. For example, when you build an app (iOS or Mac) via Xcode, it connects to CloudKit's development environment, when you build for AppStore, the app connects to the production environment. Therefore patient data is not synced between debug build and production build. You can confirm the actual data that is in the database by looking at the dashboard:

   1. Go to https://icloud.developer.apple.com/dashboard/
   2. Click "iCloud.com.ywesee.AmikoDesitin" on the left side
   3. Click "Data" in either Development / Production
   4. Click "Query Records" on the left side
   5. To see if the patients are actually there

2.
   > is the file format for Favorites the same for macOS and iOS?

   Yes, Normal Favourites and FTS Favourites is the same format. In fact, they are in the same file. So if normal favourites work, the format should be fine. I am thinking, maybe the iOS app and the Mac app is using different version of "amiko_frequency_de.db". When does it crash? Is it when you click on FTS? or Favourites? It will be great if there's a crash log.

Thank you!

**Comment by zdavatz** [comment]
<img width="717" alt="Bildschirmfoto 2020-08-10 um 18 42 30" src="https://user-images.githubusercontent.com/4953/89801749-42e2cc80-db39-11ea-888d-6670d57f91e7.png">

**Comment by zdavatz** [comment]
<img width="1429" alt="Bildschirmfoto 2020-08-10 um 18 43 47" src="https://user-images.githubusercontent.com/4953/89801935-6f96e400-db39-11ea-8a1c-f4847b6d2ac5.png">

**Comment by zdavatz** [comment]
Crash log is here: https://github.com/zdavatz/amiko-osx/issues/107

**Comment by zdavatz** [comment]
CoMed says this:
<img width="721" alt="Bildschirmfoto 2020-08-10 um 18 48 45" src="https://user-images.githubusercontent.com/4953/89802394-24310580-db3a-11ea-90b3-e72488ec51fb.png">

**Comment by zdavatz** [comment]
CoMed Production says:
<img width="1426" alt="Bildschirmfoto 2020-08-10 um 18 49 38" src="https://user-images.githubusercontent.com/4953/89802529-4c206900-db3a-11ea-8142-47fa34c60c7a.png">

**Comment by zdavatz** [comment]
there is only one `frequency_de.db` and `frequency_fr.db`

**Comment by b123400** [comment]
> CoMed says this:

Oh you will need to make it queryable: https://developer.apple.com/forums/thread/79126?answerId=398449022#398449022

> Crash log is here:

I think #107 is referring to another crash, it has nothing to do with FTS.

> there is only one frequency_de.db and frequency_fr.db

I mean, for example, Amiko on Mac is using a database generated on 1st August, 2020. And Amiko on iOS is using a database generated on 1st July, 2020. During the time, maybe some data has changed, but Amiko on iOS is not aware about that, because the database is too old.

**Comment by zdavatz** [comment]
what can we do to avoid the FTS-Favorites-Crash?

**Comment by b123400** [comment]
I am still trying to reproduce the crash, because it does not crash for me... Can you send me your `favourites` file?

**Comment by zdavatz** [comment]
I do not see a pop-up.

<img width="1433" alt="Bildschirmfoto 2020-08-10 um 19 49 47" src="https://user-images.githubusercontent.com/4953/89808331-a9201d00-db42-11ea-8dd2-072772d9e3df.png">

**Comment by zdavatz** [comment]
> I am still trying to reproduce the crash, because it does not crash for me... Can you send me your `favourites` file?

Lets first focus on [1](https://github.com/zdavatz/amiko-osx/issues/109#issue-672682673)

**Comment by b123400** [comment]
Click this and add "recordName" and "queryable".
![89808331-a9201d00-db42-11ea-8dd2-072772d9e3df](https://user-images.githubusercontent.com/127193/89808848-b9052480-db75-11ea-8621-907be0604c72.png)

**Comment by zdavatz** [comment]
like this: <img width="1119" alt="Bildschirmfoto 2020-08-10 um 19 58 09" src="https://user-images.githubusercontent.com/4953/89809150-d5886900-db43-11ea-9a1a-5cdcffa2a2b0.png">

**Comment by zdavatz** [comment]
For `production` I can not do this.

<img width="1204" alt="Bildschirmfoto 2020-08-10 um 19 59 27" src="https://user-images.githubusercontent.com/4953/89809281-036dad80-db44-11ea-8680-83e2cf0fd936.png">
