### ISSUE TITLE
Print with more then 10 packages does not show all packages.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#11]
Only the view of the frame shown is printed. Compare the two pdfs:
Before the scroll:
[Rezept.pdf](https://github.com/zdavatz/amiko-osx/files/1956386/Rezept.pdf)
After the scroll:
[Rezept after Scroll.pdf](https://github.com/zdavatz/amiko-osx/files/1956398/Rezept.after.Scroll.pdf)

Both PDFs above are the same prescription.

Reproduce:
1. Create prescription with more the 10 packages.
2. Add a comment with 1000 words or one package.
3. Do "Apple + D" and Open PDF in _Preview_.
4. Scroll in AmiKo until the last package is shown.
5. Print into _Preview_ again.
6. Compare the two PDFs.

For the print view we have to take the prescriptions out of the frame. It seems only the frame View is printed but not all its contents.

**Comment by zdavatz** [comment]
The file name of the PDF should be filename of the file (RZ_...)
<img width="1090" alt="bildschirmfoto 2018-05-03 um 08 55 07" src="https://user-images.githubusercontent.com/4953/39563291-d0ed2a8e-4eaf-11e8-92d0-c0cd3479006a.png">

**Comment by zdavatz** [comment]
See: https://stackoverflow.com/questions/13999971/cocoa-mac-os-x-printing-multiple-pages-why-is-preview-window-displaying-2-pag

**Comment by zdavatz** [comment]
Are we overriding the _runPageLayout:_ method of the _NSApplication_ class?
See: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Printing/osxp_printlayoutpanel/osxp_printlayoutpanel.html#//apple_ref/doc/uid/20000863-BAJBFGED

**Comment by zdavatz** [comment]
Also see `2. Create a view that’s used only for printing.` in the above link.

**Comment by zdavatz** [comment]
see: https://stackoverflow.com/questions/28112787/create-a-custom-cell-in-a-nstableview

**Comment by zdavatz** [comment]
**header cell = column header**
https://developer.apple.com/documentation/appkit/nstablecolumn

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/2297209/printing-the-data-in-a-nstableview Print HTML representation of the table:

**Comment by zdavatz** [comment]
Resizing the print view: https://stackoverflow.com/questions/49498622/when-to-resize-my-nsview-for-printing?rq=1

**Comment by zdavatz** [comment]
The Filename is still missing in the PDF print.
![filename_missing](https://user-images.githubusercontent.com/4953/39708744-47548a4e-5218-11e8-9d08-6c85ea3faeab.jpg)

**Comment by bettar** [comment]
You have to have the AMK selected in the right list

**Comment by zdavatz** [comment]
Works!
