### ISSUE TITLE
Dealing with old Hashes. Converting them to SHA256 at import.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#119]
See: https://github.com/zdavatz/amiko-osx/pull/117/commits/9664f86c8e4dcb2939f3409eb806b1bab31eeda3

@bettar reports, that he created amk and decoded it to json. But the SHA256 is not there. Use from commit fa0d277

**Comment by zdavatz** [comment]
@bettar says: Insight into sha256: it works if I create a new patient, for old patients it uses old hash

**Comment by bettar** [comment]
It seems reasonable that the app keeps using old hash for old patients, and uses sha256 for new patients. Is there an official policy for handling old patients and old prescriptions ? Should they be updated or left unchanged ? Note that this decision also affects the subdirectories where those amk files are stored.

**Comment by zdavatz** [comment]
Good point! When importing old Hashes, convert them to SHA256 at import.

**Comment by zdavatz** [comment]
The Linux version already does that.

**Comment by bettar** [comment]
The linux version warns about the wrong patient hash when importing, but here in the macOS version, what if they are not imported but just selected in the list of old prescriptions ? Should the old prescriptions left alone ? Should they be moved to the updated subdirectory ? Is it okay to keep creating new amk files with the old hash if an old patient is selected (this is what happens now) ? Many questions...

**Comment by zdavatz** [comment]
Good question. Maybe the Mac version can do the same like the Linux version does. Lets see if a user complains.

**Comment by bettar** [comment]
Mac version cannot do the same as the Linux version, because the Linux version doesn't have patients and prescriptions with the old hash

**Comment by zdavatz** [comment]
We need to find the problematic Use-Case for the Mac, where the User trips over an old Hash of an existing patient and when to update to the new Patient Hash and new directory Hash of SHA156.
