### ISSUE TITLE
Verbesserung #23

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#124]
@bettar says about #23: The functionality could be improved: right now the user doesn’t know that they have to enter at least the doctor name and surname to make the hint disappear

**Comment by bettar** [comment]
Also on the Patient creation panel, now that there is a nice validation at each keystroke, showing invalid fields with red background, it seems redundant to indicate the required fields with an asterisk '*'

**Comment by zdavatz** [comment]
Ok, but this is not related to this issue. The Askerisk is still useful and wanted.

**Comment by bettar** [comment]
It is related to the issue, because the doctor should also have an asterisk next to the name and surname and validate those two fields with red background if invalid

**Comment by zdavatz** [comment]
This issue is about the doctor not the patient.

**Comment by bettar** [comment]
You are right, the comments about the patient are "not related"
