### ISSUE TITLE
Cannot go back to the full list after clearing a search

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#131]
Tested with version 3.4.24 running from Xcode.
Note that this was also "broken" in old version 3.4.10

Steps to reproduce:

1. Launch app
2. search preparation for "123"
3. clear the search string clicking on the "x" symbol
4. the list of fachinfos is empty

It's worth testing also with doing first a search for a registration number, and switching to the preparation, while doing different searches and clearing them, to see if it all makes sense.

**Comment by zdavatz** [comment]
Good, this has to be fixed. Thank for the report @bettar
