### ISSUE TITLE
You should not be able to save a prescription if the doctor address is missing

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#14]
1. Create a new prescription.
2. Doctor address is missing (because of the printing updated that deleted all data).
3. Add a note to the package. 
4. Click _Save as New_.
5. Nothing happens because the doctor address is missing.
6. Ergo: Save button should be disabled as long as the doctor address is missing.

**Comment by bettar** [comment]
The problem was: the string "Bitte Arztstempel ergänzen" was mistakenly taken as a valid doctor address, and the Save button wrongly enabled because of that.
