### ISSUE TITLE
(null) shown instead of city name

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#151]
in AmiKo version 3.4.25 official release from App Store, in the prescription view, to the left of the doctor signature I always see (null) instead of the doctor's city.

There are two cases to consider:

1. if the doctor city is defined it should appear there
2. if the doctor city is not defined seeing `(null)` doesn't look good

**Comment by zdavatz** [comment]
@bettar Did you click save?

**Comment by zdavatz** [comment]
This must be related to the patient being created before we started using SHA256, see https://github.com/zdavatz/amiko-osx/issues/152

**Comment by bettar** [comment]
what’s the specifications ? showing the doctor’s city from the doctor's settings or the doctor city from the prescription ?

**Comment by zdavatz** [comment]
1. If it is imported prescription that was not changed, it should show the city of the prescription.
2. If the prescription has been imported and then the user clicked save, it should take the doctor’s city from the doctor's settings.

**Comment by bettar** [comment]
what about case number 3. clicking "new prescription" ? Is it okay to see `(null)` ?
