### ISSUE TITLE
Export Button is missing in Big Sur. Customizable toolbar is missing.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#158]
@bettar asks: is it possible to add a separator ? I mean not in the code, but when you run the app and customize the toolbar.
can you add the “Export” toolbar button ?
in macos Catalina toolbars can be customized by the user. In Big Sur they cannot be customized ? I guess it should be possible as well.

Export button is normally missing in Catalina too, unless it’s added by the user

So the bottom line is: if BigSur doesn’t allow users to customize the toolbar, the Export button should be part of the initial set of default buttons

**Comment by b123400** [comment]
Yes, you can customise toolbar on Big Sur as well.

![macOS 11 0 usb 2020-10-24 00-04-59](https://user-images.githubusercontent.com/127193/97020538-a0a98100-158c-11eb-8589-3494d3f39267.png)

**Comment by zdavatz** [comment]
Ok, thank you!
