### ISSUE TITLE
CoMed Desitin manque la Pilule bleue en haut à droite 

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#163]
Je viens de finir de manger une baguette avec du jambon parce que j’étudie Français.

J’ai testé l’application CoMed Desitin version 3.4.26

Il semble avoir la mauvaise icône dans la barre d’outils, il ressemble à la version allemande et il dit AmiKo Desitin

Parbleu !

**Comment by bettar** [comment]
![Uploading Screenshot 2020-10-27 at 16.30.12.png…]()

**Comment by zdavatz** [comment]
bien trouvé, merci!

**Comment by zdavatz** [comment]
![Bildschirmfoto 2020-10-27 um 16 55 32](https://user-images.githubusercontent.com/4953/97327648-777f3e00-1875-11eb-92db-375f56908292.png)

**Comment by bettar** [comment]
Ma langue système n’est ni Français ni allemand

**Comment by bettar** [comment]
Veuillez expliquer pourquoi ce problème a été fermé

**Comment by zdavatz** [comment]
La pillule est blue meaintenant.
![Capture d’écran 2020-10-29 à 11 26 14](https://user-images.githubusercontent.com/4953/97556398-b29a8200-19d9-11eb-85b5-f7a35fd1ee38.png)

**Comment by zdavatz** [comment]
Le default est le icon de AmiKo.
