### ISSUE TITLE
Big Sur: Icons müssen mit Text dargestellt werden

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#164]
Bei den Icons fehlt jetzt noch der Text unter den Icons:

![Bildschirmfoto 2020-10-27 um 16 52 38](https://user-images.githubusercontent.com/4953/97327958-cb8a2280-1875-11eb-8a07-0dcc82335bf5.png)

**Comment by zdavatz** [comment]
Das sieht nach einem Bug in Big Sur aus.

**Comment by zdavatz** [comment]
Wenn man die App mit Xcode startet, dann sind die Icons vorhanden.

**Comment by b123400** [comment]
Ich habe Big Sur installieren, und es gibt Text unter den Icons.
![Screen Shot 2020-11-15 at 22 39 07](https://user-images.githubusercontent.com/127193/99187154-399c7800-2798-11eb-94f4-2151ee37bd46.png)

**Comment by zdavatz** [comment]
ich werde nochmals testen, Danke!
