### ISSUE TITLE
Actuellement l'Infopro ne change pas si on ajoute une package à la préscription.

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#166]
Je viens de finir de manger une baguette avec trois escargots. Je les ai mis à 15 cm l’un de l’autre, mais ils se sont déplacés un peu sur le côté.

J’ai étudié Français à l’école S.B. Ce n’est pas la SorBonne, ce n’est pas la sœur bonne bien sur, c’est le Safari Bouton.

J’ai trouvé un petit problème avec la grande application CoMed. Il n’est pas juste qu’une grande application a un petit problème, comme mon grand cousin Norman. Il a un petit b*te.

Peut-être que le problème disparaîtra avec Big Sur bien sur. Norman adorera Big Sur.

Comment le reproduire:

1. Lancer CoMed Desitin 3.4.26 et attendre un peu. Cinq minutes, c’est bien plus que suffisant.
2. Sélectionnez un résultat dans la liste et la Notice Infopro est mis à jour. Bon.
3. Cliquez sur un paquet de médicaments dans un résultat différent, et l’ajouter à la prescription
4. Ajouter éventuellement plus de packages à partir d’autres résultats
5. Qu'est-ce qui se passe ? La Notice Infopro n’a pas changé.
6. Parbleu !

Est-ce par conception?

Jusqu’à présent, je l’ai testé sur le marché italien. La semaine prochaine, je vais me rendre à Munich et le tester sur le marché allemand. C’est incroyable que je puisse tester une application Français dans tous ces marchés. Merci Safari Bouton

Je suis en attachant une belle capture d’écran de ma version os sur le dessus de CoMed.

**Comment by bettar** [comment]
![Uploading Screenshot 2020-10-28 at 14.12.02.png…]()

**Comment by zdavatz** [comment]
Pourquoi Infopro doit changer?

**Comment by bettar** [comment]
Vous avez supprimé le texte important sur Norman dans la publication originale. Sans ce texte, il n’a pas de sens de parler de Norman. Si vous voulez imposer la censure, vous devez supprimer toutes les références sur Norman

**Comment by zdavatz** [comment]
Je pense que c'est bien comme ça pour le moment.
