### ISSUE TITLE
Containerize the print view

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#17]
address is `NSTextfield`, Signature is subclass of `NSView`, package list is `tableView`.
`tableView` is embedded in a `NSClipView` that is embedded in an `NSScrollView`
When you containerize you get more control of the view.

So now we still have to add the [pagination](http://iannopollo.com/blog/2012/11/03/print-and-paginate-nstableviews/).
[NSStackView](https://developer.apple.com/documentation/appkit/nsstackview?language=objc)

**Comment by bettar** [comment]
I tried this approach, but the tableview was rendered in unpredictable positions on the page, depending non how many medicines are listed. Also, pagination doesn't seem to work. I am not sure what I was doing wrong or missing.
