### ISSUE TITLE
Integrating Smart Card Reader Controller AU9540

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#19]
[AU9540 Datasheet](https://github.com/zdavatz/amiko-osx/files/1995096/AU9540.Datasheet.pdf), also see the Drivers for [Win/Linux/Mac](http://www.xystec.info/USB-Chipkartenleser-HBCI-faehig-Smart-Card-PX-8935-919.shtml#downloads) and the Standard for [7816-4](https://www.ech.ch/alfresco/s/ech/download?nodeid=487d3aac-fe76-44c0-a9b1-38a901cc37cd). Once the reader is plugged in, issue the command [`pcsctest`](http://b2b.ktnet.com.tw/Upload/LinkDownload/KTHCROATM003BK/AU9540,9560_pkg_for_MAC_InstallManual_20170928.pdf) on Mac.

**Comment by zdavatz** [comment]
[ATR](https://smartcard-atr.appspot.com) values can be read.

**Comment by bettar** [comment]
pcsctest

**Comment by zdavatz** [comment]
Me too, that is a typo. Sorry.

**Comment by zdavatz** [comment]
Search for _APDU_ in my links above.

**Comment by zdavatz** [comment]
[INS number](http://techmeonline.com/most-used-smart-card-commands-apdu/)

**Comment by zdavatz** [comment]
[6982:Security status not satisfied”](https://stackoverflow.com/questions/15881962/authentication-error-for-mifare-card-6982security-status-not-satisfied)

**Comment by zdavatz** [comment]
The smart-card [list](http://ludovic.rousseau.free.fr/softwares/pcsc-tools/smartcard_list.txt)

**Comment by zdavatz** [comment]
This is a Java-Tool you can also [try](https://sourceforge.net/projects/jsmartcard/)

**Comment by zdavatz** [comment]
Errors are: `69 Command not allowed` and `86 Security Status not satisfied`

**Comment by zdavatz** [comment]
complete list of [APDU](https://www.eftlab.co.uk/index.php/site-map/knowledge-base/118-apdu-response-list) responses.

**Comment by zdavatz** [comment]
Const values regarding the [ISO](https://github.com/boundary/wireshark/blob/master/epan/dissectors/packet-iso7816.c#L164) standard.

**Comment by zdavatz** [comment]
<img width="555" alt="bildschirmfoto 2018-05-18 um 15 42 19" src="https://user-images.githubusercontent.com/4953/40237948-224e8cca-5ab2-11e8-8367-607601a5528d.png">

**Comment by zdavatz** [comment]
I managed to get some data out:
<img width="1433" alt="bildschirmfoto 2018-05-18 um 18 01 21" src="https://user-images.githubusercontent.com/4953/40245287-872b8c0c-5ac5-11e8-9909-7f3baff1586b.png">

**Comment by zdavatz** [comment]
This file should clear up a lot.
[Implementierungsanleitung für die Versichertenkarte nach eCH-0064 der SASIS AG.pdf](https://github.com/zdavatz/amiko-osx/files/2018228/Implementierungsanleitung.fur.die.Versichertenkarte.nach.eCH-0064.der.SASIS.AG.pdf)

**Comment by zdavatz** [comment]
[TLV](https://www.emvlab.org/tlvutils/) decoding.

**Comment by zdavatz** [comment]
On Linux you can do:
`/usr/sbin/pcscd -a -d -f`
`opensc-explorer`

**Comment by zdavatz** [comment]
Now I can do
```
OpenSC [3F00]> info 3F00

Dedicated File  ID 3F00

File path:     3F00
File size:     0 bytes
ACL for SELECT:       N/A
ACL for LOCK:         N/A
ACL for DELETE:       N/A
ACL for CREATE:       N/A
ACL for REHABILITATE: N/A
ACL for INVALIDATE:   N/A
ACL for LIST FILES:   N/A
ACL for CRYPTO:       N/A
ACL for DELETE SELF:  N/A
Proprietary attributes:  A3 24 8F 04 00 22 81 B6 90 01 1C 8F 04 00 2A 00 AE 90 01 1D 8F 04 00 82 00 00 90 01 1E 8F 04 00 88 00 00 90 01 15 85 01 01 86 01 10
Security attributes:     A4 00 00 00 FF FF E0 00 80 00 FF FF 08 00 00 00 FF FF CA 00 00 00 FF FF FF 80 00 00 FF FF
```

**Comment by zdavatz** [comment]
So there is also a file path ;)
```
OpenSC [3F00]> info 2F00

Elementary File  ID 2F00, SFI F0

File path:     3F00/2F00
File size:     84 bytes
EF structure:  Transparent
ACL for READ:         N/A
ACL for UPDATE:       N/A
ACL for DELETE:       N/A
ACL for WRITE:        N/A
ACL for REHABILITATE: N/A
ACL for INVALIDATE:   N/A
ACL for LIST FILES:   N/A
ACL for CRYPTO:       N/A
Security attributes:     B0 00 00 00 FF FF A4 00 00 00 FF FF D6 00 80 00 FF FF
```

**Comment by zdavatz** [comment]
you can also look at the files contents with `cat`
```
OpenSC [3F00]> cat 2F01
00000000: E0 10 02 02 04 00 02 02 04 00 02 02 04 00 02 02 ................
00000010: 04 00 66 17 46 15 02 49 6E 74 65 72 31 20 20 20 ..f.F..Inter1   
00000020: 4D 54 43 4F 53 20 70 20 32 2E 31                MTCOS p 2.1
```

**Comment by zdavatz** [comment]
and I found Lionel ;
```
OpenSC [3F00]> cat 2F06
00000000: 65 33 80 15 44 61 76 61 74 7A 2C 20 4C 69 6F 6E e3..Davatz, Lion
00000010: 65 6C 20 4D 61 73 61 74 6F 82 08 32 30 31 30 30 el Masato..20100
00000020: 36 30 31 83 0D 37 35 36 38 32 37 35 37 36 32 31 601..75682757621
00000030: 36 38 84 01 01 00 00 00 00 00 00 00 00 00 00 00 68..............
00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000050: 00 00 00 00                                     ....
```

**Comment by zdavatz** [comment]
to get the sex you have to do `asn1 2f06`

**Comment by zdavatz** [comment]
This is the [AHV Nummer](https://www.bsv.admin.ch/bsv/it/home/assicurazioni-sociali/ahv/basi-giuridiche-e-legislazione/come-e-strutturato-il-numero-d-assicurato-.html)

**Comment by zdavatz** [comment]
Add or delete columns to existing [sqlitedb](https://www.sqlite.org/faq.html#q11).

**Comment by zdavatz** [comment]
Todos:
- [ ] inserting SmarCard if patient according to AHV number already exists automatically selects the patient for the prescription. No patient Sheet is shown.
- [ ] inserting the SmartCard if patient according to AHV number des _not_ yet exist: A new table is created with the Hash and the AHV-Number.

**Comment by zdavatz** [comment]
Remaining Issues: Patient A is not selected if already in the database after making a prescription for another patient.
1. Start the App
2. Enter the card form patient A.
3. Patient sheet of A opens with the data filled in should be shown.
4. Add required information to the patient A.
5. Save the patient A.
6. Make a prescription. Save the prescription of patient A.
7. Select patient B. Add a package for him. Save the prescription of patient B.
8. Enter the card again from patient A.
9. Patient A is not selected selected in the patient sheet.

**Comment by bettar** [comment]
As we mentioned earlier on, at the moment the pre-filling of the patient data works reliably only if the patient sheet is already open. It needs to be improved.

**Comment by zdavatz** [comment]
That actually now always works just fine. Just when the patient A from the card has been saved it does not work anymore, after working with patient B. See above.

**Comment by zdavatz** [comment]
So the Use-Cases that remain are:
1. If Patient A is in the Database and the doctor inserts the card, patient A should be set as patient without opening the patient sheet.
2. If patient A is in the database and the patient sheet is open and the doctor inserts the card then the patient sheet should be closed and patient A should be selected for the prescription.
