### ISSUE TITLE
Invoice is missing the prices of the drugs.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#197]
1. Create a prescription that has a drug that has a PP price.
2. This XML is created: [medidata_test_2.xml.txt](https://github.com/zdavatz/amiko-osx/files/6872664/medidata_test_2.xml.txt)
3. The drug that has to be invoiced is missing in the invoice xml.
4. <img width="980" alt="Bildschirmfoto 2021-07-24 um 18 29 14" src="https://user-images.githubusercontent.com/4953/126873288-60c335bd-bd4a-4bf6-88a2-fd599604b232.png">
5. See https://github.com/zdavatz/amiko-osx/issues/179#issuecomment-875892122 Point 10.
6. This can never be 0. <img width="694" alt="Bildschirmfoto 2021-07-28 um 12 53 32" src="https://user-images.githubusercontent.com/4953/127302802-e0554c48-c50e-47da-b7fb-321f12d01e24.png">

**Comment by b123400** [comment]
This is the file I get: [Untitled.txt](https://github.com/zdavatz/amiko-osx/files/6892782/Untitled.txt)
It has the price

**Comment by zdavatz** [comment]
Ok, so why do I never get any packages in my XML?
