### ISSUE TITLE
Dynamically adjust button width to Text size

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#20]
The width of the buttons has to be dynamically adjusted to the length of the text. Otherwise the buttons look terrible. See [SizeToFit](https://stackoverflow.com/questions/7212553/automatically-resize-an-nsbutton-to-fit-programmatically-changed-text-xcode).

**Comment by bettar** [comment]
Which buttons are we talking about ?

**Comment by zdavatz** [comment]
The buttons in the prescription. The look terrible at the moment. They are either to wide or to narrow. One is also still cut off. So lets just adjust the size of the Button to the Text length.

**Comment by zdavatz** [comment]
<img width="604" alt="bildschirmfoto 2018-05-14 um 10 06 38" src="https://user-images.githubusercontent.com/4953/39985368-bbb70e70-575e-11e8-91e4-427f5ca08bf2.png">

**Comment by zdavatz** [comment]
Same goes for CoMed btw.

**Comment by zdavatz** [comment]
The official Apple documentation for [sizeToFit](https://developer.apple.com/documentation/appkit/nscontrol/1428877-sizetofit?language=objc)

**Comment by zdavatz** [comment]
Another [sizeToFit](https://stackoverflow.com/questions/29623902/nstextfield-sizetofit-or-frame-update-shift-text-to-left) person talks about _subclassing_.

**Comment by bettar** [comment]
Maybe now you can even go back to the original non-abbreviate text for the button labels.

**Comment by zdavatz** [comment]
Let me try that.
