### ISSUE TITLE
Set filename for XML

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#203]
1. Set the filename for the XML.
2. The filename should be: "First name"`_`"Last name"`_`"Date of Birth: dd.mm.yyyy"`_`"Timestamp: hh:mm:dd:mm:yyyy".xml
3. <img width="446" alt="Bildschirmfoto 2021-07-28 um 12 46 56" src="https://user-images.githubusercontent.com/4953/127303279-f98faa19-108d-474d-9e65-e84c5d71e12d.png">

**Comment by bettar** [comment]
On 28/07/21 11:57, Zeno R.R. Davatz wrote:
> _"Timestamp: hh:mm:dd:mm:yyyy"

This timestamp doesn't make good sense

**Comment by zdavatz** [comment]
> On 28/07/21 11:57, Zeno R.R. Davatz wrote: _"Timestamp: hh:mm:dd:mm:yyyy"
> This timestamp doesn't make good sense

What would you suggest then?

**Comment by bettar** [comment]
- Use a different symbol for month and for minutes (HH for hours and MM
for minutes)
- Use a different separator between time and date
- Reverse the order so that the alphabetical sorting is the same as the
chronological sorting
- Make it clear whether the time is local time or UTC time
