### ISSUE TITLE
Language settings are not working for the CoMed release

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#22]
Language settings are not working for the CoMed release. CoMed Release is still all in English.

**Comment by bettar** [comment]
Are you sure you are not running CoMed in an English environment ?

**Comment by zdavatz** [comment]
Build CoMed and then then try changing the language of your Mac. The buttons in CoMed always stay English.

**Comment by zdavatz** [comment]
This should say _ordonnance_.
<img width="514" alt="bildschirmfoto 2018-05-14 um 11 31 36" src="https://user-images.githubusercontent.com/4953/39989502-6d2aaa3a-576a-11e8-9329-3c579cc26e8d.png">
