### ISSUE TITLE
Check for ATR

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#38]
Revolut Card crashes AmiKo App.

This is the ATR of another insurance company. 

`3B 9F 13 81 B1 80 37 1F 03 80 31 F8 69 4D 54 43 4F 53 70 02 01 02 81 07 86`

It looks the same as the first one.

**Comment by zdavatz** [comment]
Expected Outcome: If the ATR is not correct exit with the following message.

`This card can not be read, please contact Zeno Davatz, zdavatz@ywesee.com, +41 43 540 05 50`.

**Comment by zdavatz** [comment]
Then include the ATR in the screen.

**Comment by bettar** [comment]
As usual, how about the French and German versions ?

**Comment by zdavatz** [comment]
French: 
`Cette carte ne peu pas être lire. S.v.p. contactez Zeno Davatz, zdavatz@ywesee.com, +41 43 540 05 50`

**Comment by zdavatz** [comment]
German:
`Diese Karte kann nicht gelesen werden. Bitte kontaktieren Sie Zeno Davatz, zdavatz@ywesee.com, +41 43 540 05 50`
