### ISSUE TITLE
Use `SHA256` for hashed value.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#43]
* Use `SHA256` for hashed value.
* Make source string lowercase (`Davatz`, `DAVATZ` -> `davatz`).

See https://github.com/zdavatz/amiko_csharp/issues/81#issuecomment-396128272

**Comment by zdavatz** [comment]
Sample of C# how it is done: https://github.com/zdavatz/amiko_csharp/commit/c665ae461c253d87872911cd74a39acbe4be9b12

**Comment by bettar** [comment]
Isn't this change going to make all the prescriptions created so far invalid ?

**Comment by zdavatz** [comment]
see: https://stackoverflow.com/questions/4992109/generate-sha256-string-in-objective-c
