### ISSUE TITLE
Enable iCloud Sync

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#74]
Enable iCloud Sync, so you can sync your data with the AmiKo for iOS or just backup to the cloud as with the iPhone.

**Comment by b123400** [comment]
Meine Todo-Liste.
- Local -> iCloud Migration:
  - [ ] Amk Dateien kopieren
  - [x] Arzt Dateien kopieren 
  - [ ] Patienten vom Sqlite zu CloudKit kopieren
- Cloud -> Local Migration
  - [ ] Amk Dateien kopieren
  - [x] Arzt Dateien kopieren 
  - [ ] Patienten vom CloudKit zu Sqlite kopieren
  - [x] Dateien auf iCloud löschen
----
- [x] Arzt Datei lesen
- [x] Arzt Datei schreiben 
- [x] Arzt "signature.png" Datei lesen 
- [x] Arzt "signature.png" Datei schreiben
- [ ] Amk Dateien lesen
- [ ] Amk Dateien schreiben
- [ ] Patienten lesen
- [ ] Patienten schreiben
----
- UI updaten wann iCloud dateien geändert
  - [ ] Arzt
  - [ ] Prescription
  - [ ] Patienten Liste
  - [ ] Patient
  - [ ] AMK liste
----
- [ ] Prescription import
- [ ] Setting View

**Comment by b123400** [comment]
@zdavatz  Wir benutzen [CloudKit](https://developer.apple.com/documentation/coredata/nspersistentcloudkitcontainer?language=objc) für Mac für Patienten Synchronisation, aber ist das nur verfügbar auf Mac OS 10.15. Wir kann es so machen:

1. Ältere OS kann noch die App laufen, mit Arzt/AMK Synchronisation etc, aber ohne Patienten Synchronisation.

2. Ältere OS kann nicht die App laufen.

Welche mögen Sie?

**Comment by zdavatz** [comment]
iCloud muss nur ab macOS 10.15. funktionieren.

**Comment by zdavatz** [comment]
10.14 gar keine Synchronisation.
