### ISSUE TITLE
Interactions and Full text: does it make sense ?

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#81]
Steps to reproduce
- Interactions, Preparations, add one medicine
- Interactions, Full text, search for "sapp", select one result
- Problem 1: the Interactions view is replaced by something else
- Problem 2: the Interactions toolbar button remains selected

**Comment by zdavatz** [comment]
it should add to the interactions. This is a bug.

**Comment by bettar** [comment]
Why has this issue been closed ? Has it been tested at all ? To me it looks like the problem is still there with version 3.4.16

**Comment by zdavatz** [comment]
<img width="1364" alt="Bildschirmfoto 2020-07-27 um 12 14 12" src="https://user-images.githubusercontent.com/4953/88525061-cdd4aa80-d002-11ea-828c-22ab72617ace.png">

**Comment by b123400** [comment]
For problem 1:

1. When you go to Interactions, the center view is showing interactions.
2. When you search for "sapp" for Full text, you see many results, e.g. "sappinfo, 144 Treffer".
3. "sappinfo" has 144 hits, which one should we add to interactions? We need to select one of the 144 hits, so we show them the result in the center view.
4. When the user click any result of the center view, the clicked result is added to the interaction view.

Which step is wrong?

**Comment by zdavatz** [comment]
>     3. "sappinfo" has 144 hits, which one should we add to interactions? We need to select one of the 144 hits, so we show them the result in the center view.

Actually here we could just always add the first product of each ATC-Code, as the interactions are based on ATC-Codes.
