### ISSUE TITLE
Interaktionen

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#85]
What's the intended behaviour for the "Interaktionen" (Interactions) view ? should it list only the medicines added to the current "Rezept" (prescription) or all the medicines viewed so far in the Compendium ?

Now it appears that any medicine for which we display the Fachinfo from the Compendium is automatically added to the list of Interactions.

To me it would make more sense if we had the following 2 cases:

1. Compendium view only displays the Fachinfo, for any of the 6 search modes. Of course it's possible to add to the Prescription by selecting the "package"
2. Interaction view adds to the list of interactions, for any of the 6 search modes

A specifications document outlining the intended behaviour would be greatly appreciated.

**Comment by zdavatz** [comment]
> What's the intended behaviour for the "Interaktionen" (Interactions) view ? should it list only the medicines added to the current "Rezept" (prescription) or all the medicines viewed so far in the Compendium ?

List only medicines added to the current Prescription.

**Comment by bettar** [comment]
Then we have a bug, right ?

**Comment by zdavatz** [comment]
Yes. It seems every product selected in the compendium view is added to the interactions view, somhow magically. This should not happen.

**Comment by zdavatz** [comment]
Actually no, this is not a bug. This only happens if you come from the interactions basket.

**Comment by bettar** [comment]
Not completely true, even if I stay in the Compendium view, the last item viewed is added to the Interactions. Quite confusing.

**Comment by zdavatz** [comment]
Yes, if you come fromt the interactions view.

**Comment by bettar** [comment]
It's added even if I don't come from the Interactions view

**Comment by zdavatz** [comment]
I can not yet confirm this.

**Comment by bettar** [comment]
- Start the app
- select one result to display the fachinfo
- switch to interaction view, one item is listed

**Comment by zdavatz** [comment]
Ok, I can confirm, this is a but and should not happen.
