### ISSUE TITLE
Medikamentenkorb

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#86]
If we launch the application and go to Interaction view, it says "Ihr Medikamentenkorb ist leer." (Your medicine basket is empty).

1. What's the definition for "Medikamentenkorb" ? Is it the list of interactions ?
3. Is it related to the medicines in the current "Rezept" (prescription) ?

A specifications document outlining the intended behaviour would be greatly appreciated.

**Comment by zdavatz** [comment]
It means, that now packages have been added to the interactions basket.

**Comment by bettar** [comment]
Is the Interaction basket unrelated to the medicines in the prescription ?

**Comment by zdavatz** [comment]
Yes, the packages in the prescription have to be added to the interactions basket, if the user changes the view, but that works.

**Comment by zdavatz** [comment]
What really has to work is this button. And that seems to work.
<img width="833" alt="Bildschirmfoto 2020-07-27 um 12 57 22" src="https://user-images.githubusercontent.com/4953/88529630-f1025880-d008-11ea-850f-99582eab95a4.png">

**Comment by bettar** [comment]
So, unless we click that button, the medicines from the prescription shouldn't be listed in the Interactions ?

**Comment by zdavatz** [comment]
that is undecided.

**Comment by bettar** [comment]
In summary, if we click the button in the prescription view, the Interactions will be reset and show only the medicines from the prescription.
If we don't click the button, it's not decided whether or not the Interactions should include the entries from the current prescription. Correct ?

**Comment by zdavatz** [comment]
correct.

**Comment by bettar** [comment]
Great clarification.
As a historical note, the source code relating to the "Medikamentenkorb" has some commented-out lines indicating that at one stage there were 3 of them. Now there is only one.

**Comment by zdavatz** [comment]
> Great clarification.
> As a historical note, the source code relating to the "Medikamentenkorb" has some commented-out lines indicating that at one stage there were 3 of them. Now there is only one.

possible.

**Comment by zdavatz** [comment]
So lets be even clearer:

1. If we click the button in the prescription view, the Interactions will be reset and show only the medicines from the prescription.
2. If we don't click the button, nothing is added.
3. The user can still add packages to the interaction basket in the interaction view.
