### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#87]
The search results for all 6 types (Pra, Inh, Wir, Zul, The, Vol) in all 4 views (Kom, Fav, Int, Rez) are presented with a title (larger font, the same for all 6 types) and a list of 1 or more entries giving details that is different for each search type. Each detail item appears as clickable, but for 4 of the 6 search types it doesn't appear to do anything ?

Is this intentional, to have dead links for 4 of the 6 search results ?

**Comment by zdavatz** [comment]
Screenshot please.

**Comment by bettar** [comment]
![Screenshot 2020-07-27 at 11 24 36](https://user-images.githubusercontent.com/9733270/88526213-f0af9080-cffb-11ea-8c0f-92b0259eac55.png)
Just an example, the arrow shows a link that doesn't nothing

**Comment by zdavatz** [comment]
no, this is not intentional. They can be disabled.

**Comment by bettar** [comment]
In other words, for 4 of the 6 search types they could be displayed as a plain list, without clickable appearance ?

**Comment by zdavatz** [comment]
> In other words, for 4 of the 6 search types they could be displayed as a plain list, without clickable appearance ?

Yes, we only need the clickable links for adding packages to the prescription or for selecting ATC-Codes, see: https://github.com/zdavatz/amiko-web/issues/26

**Comment by bettar** [comment]
Selecting ATC-Codes ? Lets's not add to the confusion my talking about iOS and Android. What should clicking the link do in amiko-osx ?

**Comment by zdavatz** [comment]
Clicking the ATC-Code currently only works for AmiKo-Web, iOS and Android.

**Comment by bettar** [comment]
So in which cases the links work in amiko-osx ? Pra and Vol ?

**Comment by zdavatz** [comment]
Only for Präparat, adding a package to a prescription.

**Comment by bettar** [comment]
Now they appear as links also in the Full Text results (VOL). Are you saying that this is a bug ?

**Comment by zdavatz** [comment]
It is not a bug. The implementation was just never finished, to disable the links, after we added the selection of the packages.

**Comment by zdavatz** [comment]
If the user clicks that button, are they listed “exclusively" to the interactions basket.

**Comment by bettar** [comment]
To me it looks like it's working fine and at least that part is completed. In summary the sub-items listed as search results are clickable for 2 sears types Pro and Vol. The other 4 search results should present the results as plain list, not clickable list. Correct ?

**Comment by zdavatz** [comment]
screenshot please.

**Comment by bettar** [comment]
Maybe here we could start a new issue, but consider the following:

we ascertained that
- each search result can be clicked in the title
- search results of PRA and VOL can also be clicked in the list of items
- the only way of adding a medicine package to a prescription is clicking it in the list

Consequently the following combinations are useless because any clicking produces no effect:
- Prescription view, with any of these search modes: Owner, ATC. RegN, Therapy

Question: should they be disabled or greyed out somehow ?

**Comment by zdavatz** [comment]
they should be not clickable.

**Comment by bettar** [comment]
What are you referring to with "they" the tiles or the items in the list ?

**Comment by zdavatz** [comment]
<img width="425" alt="Bildschirmfoto 2020-07-27 um 15 41 10" src="https://user-images.githubusercontent.com/4953/88542806-b22bcd00-d01f-11ea-95dd-72ac3eb3e990.png">

**Comment by zdavatz** [comment]
Clicking for example on the company should create a new search for all products of that company.

**Comment by bettar** [comment]
2 hours ago we reached the consensus that "The other 4 search results should present the results as plain list, not clickable list". Has this changed again ?

**Comment by zdavatz** [comment]
https://github.com/zdavatz/amiko-osx/issues/90

**Comment by zdavatz** [comment]
Generally speaking:
1. Clicking on a company link should show all products of that company.
1.1 For the interactions view it will add the first product of each ATC-Code into the interactions basket.
2. Clicking on a ATC-Code link should show all products with the same ATC-Code.
2.1 For the interactions view it will add the first product of each ATC-Code into the interactions basket.
3. Clicking on a registration number link in the list should do nothing.
3.1 For the interactions view clicking on a registration number link in the list should do nothing.
4. Clicking on a Therapy link should add the same word to the search bar
<img width="418" alt="Bildschirmfoto 2020-07-27 um 19 24 59" src="https://user-images.githubusercontent.com/4953/88566769-26c23400-d03f-11ea-9055-60ff38f5aa5a.png">
4.1 For the interactions view it should then all the first product of each ATC-Code into the interaction basket.
5. For FTS 
<img width="622" alt="Bildschirmfoto 2020-07-27 um 19 27 37" src="https://user-images.githubusercontent.com/4953/88566988-84ef1700-d03f-11ea-9d73-6274144a204b.png">
