### ISSUE TITLE
Neue Datenbank wird nicht mit neuer App verteilt, oder wahrscheinlich am falschen Ort entpackt.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#88]
Ich habe https://github.com/zdavatz/amiko-osx/blob/master/scripts/build.sh laufen lassen mit `#STEP_REMOVE_SUPPORT_FILES=true` und `#STEP_DOWNLOAD_SUPPORT_FILES=true`. Wenn ich jetzt das neue App via dem App-Store installiere, dann kommen die neune Daten nicht. Es werden immer noch die alten Daten verwendet.

Wahrscheinlich werden die neuen Daten, welche mit dem Binary verteilt werden, am falschen Ort entpackt, wenn die App via Store installiert wird.

**Comment by bettar** [comment]
Most likely. Sandboxed apps have a different set of user accessible directories. By the way, did you mean `STEP_REMOVE_SUPPORT_FILES=true`
`STEP_DOWNLOAD_SUPPORT_FILES=true` that is, without the hash prefix ?

**Comment by zdavatz** [comment]
yes, those steps I enabled.

**Comment by b123400** [comment]
It seems like the app does not copy files from bundle to document folder at all, I cannot find the related logic. Will be adding it.
