### ISSUE TITLE
make ATC-Code clickable, same like in AmiKo-Web, generating an ATC search result.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#89]
see: https://github.com/zdavatz/amiko-web/issues/26

If you click that ATC-Code, then that should be equivalent to long-tapping in iOS/Android. It should generate the search result based on that ATC-Code.

<img width="608" alt="Bildschirmfoto 2020-07-27 um 15 36 15" src="https://user-images.githubusercontent.com/4953/88542463-2023c480-d01f-11ea-9116-67ad870f9bee.png">

The view is `Compendium`->`Wirkstoff/ATC Code`

**Comment by bettar** [comment]
So it behaves like "refining" the same type of search, right ?

**Comment by zdavatz** [comment]
correct.
