### ISSUE TITLE
click for company search results

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#90]
This should show all products of that company.

1. Click on the company name when the search result is sorted by `Inhaberin`
2. It is like putting the company name you clicked into the search field. The search is regenerated by the company name you clicked.
3. Step 3 would be to show all products of that company.

<img width="500" alt="Bildschirmfoto 2020-07-27 um 19 38 33" src="https://user-images.githubusercontent.com/4953/88568021-fa0f1c00-d040-11ea-956c-c9d768d4fde7.png">

**Comment by bettar** [comment]
"Show all products of that company" how ? in the Fachinfo view ?

**Comment by zdavatz** [comment]
<img width="493" alt="Bildschirmfoto 2020-07-30 um 13 29 44" src="https://user-images.githubusercontent.com/4953/88912980-cd3d4d80-d268-11ea-8004-5ef279f25e82.png">
