### ISSUE TITLE
Suchfeld in der Rezeptansicht funktioniert nicht

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-osx#94]
In der Rezeptansicht kann man auch `Ctrl+F`machen. Die Suche funktioniert dann aber nicht. Es sieht so aus, als würde es irgendwo anders suchen.

<img width="1416" alt="Bildschirmfoto 2020-07-28 um 11 53 15" src="https://user-images.githubusercontent.com/4953/88642344-08087f80-d0c9-11ea-8589-2be699f4b6a4.png">

**Comment by b123400** [comment]
Es ist das Suchfeld für das Kompendium. Solle ich das Suchfeld für Rezeptansicht löschen, oder was sollt es etwas suchen?

**Comment by zdavatz** [comment]
Es sollte einfach im Rezept suchen.
