### ISSUE TITLE
Interactions, Full text search, chapter list

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#98]
Amiko-osx 3.4.16
commit 31d3caa
Running from Xcode, Debug build

Steps to reproduce:
- Launch app and wait a couple of seconds for the results on the left to appear
- Interactions, Full text, search for "sapp"
- in the 1st result click on the title, lots of items are added to the interactions
- in the chapter list on the right, click for example on "Flucazol"

PROBLEM: the interaction view becomes blank. The anchors do not work.

**Comment by zdavatz** [comment]
actually this works for me.

**Comment by zdavatz** [comment]
<img width="1416" alt="Bildschirmfoto 2020-07-30 um 13 20 43" src="https://user-images.githubusercontent.com/4953/88912192-9c104d80-d267-11ea-94b7-0f1c5ab03373.png">

**Comment by zdavatz** [comment]
Ich kann das reproduzieren. Das Problem tritt auf, wenn man nicht zuerst auf `Korb leeren` klickt.
