### ISSUE TITLE
Feature request: visual indication of current search mode

### ISSUE THREAD

**Issue by bettar** [zdavatz/amiko-osx#99]
If the search string is empty the placeholder text gives a good hint of the type of search is going to happen. This is great.

Problem: it's very easy to forget which search type is the current one especially after switching around the view with the toolbar buttons

My personal preference would be to replace the set of 6 search buttons with a group of 6 radio buttons. Alternatively the current button should at least stay highlighted.

**Comment by zdavatz** [comment]
@bettar says: 

> That has always been my personal preference, but for amiko-wx we decided to keep the buttons, because you want to be able to click in the space all the way to the right edge. With radio buttons I’m afraid you would have to click on the text. Anyway, amiko-wx already makes a nice highlighting, so this issue only concern amiko-osx
